### PR TITLE
Test pipeline libraries

### PR DESCRIPTION
**Pull request by IsaackMwenda**
Hi @as2388 have added the pipeline libraries and ws dataset scheme PTAL!

### CODE REVIEW

**Comment by as2388** [comment]
@IsaackMwenda some of the files in lib/ are reusable as-is, but many contain project-specific code. For this reason, could you instead add the files in lib/ only when they are needed by the rest of the pipeline? I think for now you could submit, in separate PRs:
 - The WS scheme
 - The pipeline configuration/test_schemes

Add analysis_keys when you submit the analysis_file, and the icr_tools when you submit auto_code_show_messages etc.

Thanks

**Comment by IsaackMwenda** [comment]
Thanks @as2388  what do you mean by * The pipeline configuration/test_schemes?

**Comment by as2388** [comment]
> Thanks @as2388 what do you mean by * The pipeline configuration/test_schemes?

A PR containing:
 - pipeline_configurations.py
 - test_schemes.py

**Comment by IsaackMwenda** [comment]
Thanks

**Pull request closed without merging**
